# Change these first
owner: gabialabs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Gabia.www
    url: https://www.gabia.com/
  - name: Hiworks.www
    url: https://hiworks.com/
  - name: Gabia.cloud
    url: https://cloud.gabia.com/
  - name: Gabia.gcloudconsole
    url: https://gcloud.gabia.com/
  - name: Gabia.orggcloudconsole
    url: https://orgcloud.gabia.com/login
  - name: kns.kornet.net DNS 1
    check: "tcp-ping"
    url: 168.126.63.1
    port: 53
  - name: kns2.kornet.net DNS 2
    check: "tcp-ping"
    url: 168.126.63.2 
    port: 53
  - name: ns.lgtelecom.com DNS 1
    check: "tcp-ping"
    url: 164.124.101.2
    port: 53    
  - name: ns1.lgtelecom.com DNS 2
    check: "tcp-ping"
    url: 164.124.101.31
    port: 53   
  - name: bns1.hananet.net DNS 1
    check: "tcp-ping"
    url: 210.220.163.82
    port: 53
  - name: bns2.hananet.net DNS 2
    check: "tcp-ping"
    url: 219.250.36.130 
    port: 53
  - name: dns.msftncsi.com DNS 1
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: one.one.one.one DNS 1
    check: "tcp-ping"
    url: 1.0.0.1
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: g-check.zasfe.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /



# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
